-- Entrena Mente · Catálogo oficial de carreras (reemplaza por completo los datos de ejemplo).
--
-- Se corre DESPUÉS de 20260927000000_catalogo_escuelas.sql (ya aplicada).
-- Pegar completo en Supabase → SQL Editor → Run. Todo va en una transacción: si algo falla, no cambia nada.
--
-- Qué hace:
--   1. BORRA todo el catálogo actual (instituciones, áreas y carreras).
--   2. Escribe el documento oficial: UNAM, IPN, UAM, UdeG, UANL, BUAP (342 carreras) + TOEFL.
--
--   · Una carrera puede repetirse en la misma institución si está en otra área (IPN Ingeniería Ambiental,
--     UAM Comunicación Social): mismo nombre, distinto id, cada una con su guía de estudio.
--   · Áreas: UNAM A1–A4, IPN A1–A3, UAM por división (CBI, CBS…), UdeG por centro (CUCEI, CUCS…),
--     UANL A1–A6, BUAP A1–A4. El código es el 2º bloque del ID de reactivo.
--   · Las carreras que ya existían y vienen en el documento conservan su id (unam-medicina, ipn-sistemas…),
--     así las metas de student_goals e invites siguen apuntando a una carrera válida.
--   · UVM y TEC desaparecen: si alguien las tenía como meta, ese id queda sin carrera en el catálogo.

begin;

-- ═════════════════════════ 1. Borrar el catálogo actual ═════════════════════════

delete from public.carreras;
delete from public.areas;
delete from public.instituciones;

-- ═════════════════════════ 2. Unicidad por área ═════════════════════════

drop index public.carreras_nombre_unico;
create unique index carreras_nombre_unico
  on public.carreras (institucion_id, coalesce(area_id, ''), lower(trim(nombre)));

-- ═════════════════════════ 3. Instituciones ═════════════════════════

insert into public.instituciones (id, clave, nombre, tipo, color_id, orden) values
  ('unam',  'UNAM',  'Universidad Nacional Autónoma de México',    'universidad',     'unam', 10),
  ('ipn',   'IPN',   'Instituto Politécnico Nacional',             'universidad',     'ipn',  20),
  ('uam',   'UAM',   'Universidad Autónoma Metropolitana',         'universidad',     'uam',  30),
  ('udg',   'UDG',   'Universidad de Guadalajara',                 'universidad',     'udg',  40),
  ('uanl',  'UANL',  'Universidad Autónoma de Nuevo León',         'universidad',     null,   50),
  ('buap',  'BUAP',  'Benemérita Universidad Autónoma de Puebla',  'universidad',     null,   60),
  ('toefl', 'TOEFL', 'Test of English as a Foreign Language',      'examen_especial', null,   70);

-- ═════════════════════════ 4. Áreas ═════════════════════════

insert into public.areas (id, institucion_id, codigo, nombre, orden) values
  ('unam-a1', 'unam', 'A1', 'Ciencias Físico-Matemáticas y de las Ingenierías', 1),
  ('unam-a2', 'unam', 'A2', 'Ciencias Biológicas, Químicas y de la Salud', 2),
  ('unam-a3', 'unam', 'A3', 'Ciencias Sociales', 3),
  ('unam-a4', 'unam', 'A4', 'Humanidades y de las Artes', 4),
  ('ipn-a1', 'ipn', 'A1', 'Ingeniería y Ciencias Físico Matemáticas', 1),
  ('ipn-a2', 'ipn', 'A2', 'Ciencias Médico Biológicas', 2),
  ('ipn-a3', 'ipn', 'A3', 'Ciencias Sociales y Administrativas', 3),
  ('uam-cbi', 'uam', 'CBI', 'Ciencias Básicas e Ingeniería', 1),
  ('uam-cbs', 'uam', 'CBS', 'Ciencias Biológicas y de la Salud', 2),
  ('uam-csh', 'uam', 'CSH', 'Ciencias Sociales y Humanidades', 3),
  ('uam-cad', 'uam', 'CAD', 'Ciencias y Artes para el Diseño', 4),
  ('uam-ccd', 'uam', 'CCD', 'Ciencias de la Comunicación y Diseño', 5),
  ('uam-cni', 'uam', 'CNI', 'Ciencias Naturales e Ingeniería', 6),
  ('udg-cucei', 'udg', 'CUCEI', 'Ciencias Exactas e Ingenierías', 1),
  ('udg-cucs', 'udg', 'CUCS', 'Ciencias de la Salud', 2),
  ('udg-cucea', 'udg', 'CUCEA', 'Económico Administrativas', 3),
  ('udg-cucsh', 'udg', 'CUCSH', 'Ciencias Sociales y Humanidades', 4),
  ('udg-cuaad', 'udg', 'CUAAD', 'Arte, Arquitectura y Diseño', 5),
  ('udg-cucba', 'udg', 'CUCBA', 'Biológicas y Agropecuarias', 6),
  ('uanl-a1', 'uanl', 'A1', 'Ciencias de la Salud', 1),
  ('uanl-a2', 'uanl', 'A2', 'Ingeniería y Tecnología', 2),
  ('uanl-a3', 'uanl', 'A3', 'Ciencias Exactas', 3),
  ('uanl-a4', 'uanl', 'A4', 'Ciencias Sociales y Humanidades', 4),
  ('uanl-a5', 'uanl', 'A5', 'Ciencias Económico-Administrativas', 5),
  ('uanl-a6', 'uanl', 'A6', 'Arquitectura, Diseño y Artes', 6),
  ('buap-a1', 'buap', 'A1', 'Exactas e Ingenierías', 1),
  ('buap-a2', 'buap', 'A2', 'Ciencias Naturales y de la Salud', 2),
  ('buap-a3', 'buap', 'A3', 'Ciencias Sociales y Económico-Administrativas', 3),
  ('buap-a4', 'buap', 'A4', 'Humanidades y Artes', 4);

-- ═════════════════════════ 5. Carreras ═════════════════════════

insert into public.carreras (id, institucion_id, area_id, nombre, orden) values
  ('unam-actuaria', 'unam', 'unam-a1', 'Actuaría', 1),
  ('unam-arquitectura', 'unam', 'unam-a1', 'Arquitectura', 2),
  ('unam-arquitectura-de-paisaje', 'unam', 'unam-a1', 'Arquitectura de Paisaje', 3),
  ('unam-ciencia-de-datos', 'unam', 'unam-a1', 'Ciencia de Datos', 4),
  ('unam-ciencia-de-materiales-sustentables', 'unam', 'unam-a1', 'Ciencia de Materiales Sustentables', 5),
  ('unam-ciencias-de-la-computacion', 'unam', 'unam-a1', 'Ciencias de la Computación', 6),
  ('unam-ciencias-de-la-tierra', 'unam', 'unam-a1', 'Ciencias de la Tierra', 7),
  ('unam-diseno-industrial', 'unam', 'unam-a1', 'Diseño Industrial', 8),
  ('unam-fisica', 'unam', 'unam-a1', 'Física', 9),
  ('unam-fisica-biomedica', 'unam', 'unam-a1', 'Física Biomédica', 10),
  ('unam-geociencias', 'unam', 'unam-a1', 'Geociencias', 11),
  ('unam-ingenieria-aeroespacial', 'unam', 'unam-a1', 'Ingeniería Aeroespacial', 12),
  ('unam-ingenieria-ambiental', 'unam', 'unam-a1', 'Ingeniería Ambiental', 13),
  ('unam-ingenieria-civil', 'unam', 'unam-a1', 'Ingeniería Civil', 14),
  ('unam-ingenieria-de-minas-y-metalurgia', 'unam', 'unam-a1', 'Ingeniería de Minas y Metalurgia', 15),
  ('unam-ingenieria-electrica-electronica', 'unam', 'unam-a1', 'Ingeniería Eléctrica Electrónica', 16),
  ('unam-ing-computacion', 'unam', 'unam-a1', 'Ingeniería en Computación', 17),
  ('unam-ingenieria-en-energias-renovables', 'unam', 'unam-a1', 'Ingeniería en Energías Renovables', 18),
  ('unam-ingenieria-en-sistemas-biomedicos', 'unam', 'unam-a1', 'Ingeniería en Sistemas Biomédicos', 19),
  ('unam-ingenieria-en-telecomunicaciones', 'unam', 'unam-a1', 'Ingeniería en Telecomunicaciones', 20),
  ('unam-ingenieria-en-telecomunicaciones-sistemas-y-electronica', 'unam', 'unam-a1', 'Ingeniería en Telecomunicaciones, Sistemas y Electrónica', 21),
  ('unam-ingenieria-geofisica', 'unam', 'unam-a1', 'Ingeniería Geofísica', 22),
  ('unam-ingenieria-geologica', 'unam', 'unam-a1', 'Ingeniería Geológica', 23),
  ('unam-ingenieria-geomatica', 'unam', 'unam-a1', 'Ingeniería Geomática', 24),
  ('unam-ingenieria-industrial', 'unam', 'unam-a1', 'Ingeniería Industrial', 25),
  ('unam-ingenieria-mecanica', 'unam', 'unam-a1', 'Ingeniería Mecánica', 26),
  ('unam-ingenieria-mecanica-electrica', 'unam', 'unam-a1', 'Ingeniería Mecánica Eléctrica', 27),
  ('unam-ingenieria-mecatronica', 'unam', 'unam-a1', 'Ingeniería Mecatrónica', 28),
  ('unam-ingenieria-petrolera', 'unam', 'unam-a1', 'Ingeniería Petrolera', 29),
  ('unam-ingenieria-quimica', 'unam', 'unam-a1', 'Ingeniería Química', 30),
  ('unam-ingenieria-quimica-metalurgica', 'unam', 'unam-a1', 'Ingeniería Química Metalúrgica', 31),
  ('unam-matematicas', 'unam', 'unam-a1', 'Matemáticas', 32),
  ('unam-matematicas-aplicadas', 'unam', 'unam-a1', 'Matemáticas Aplicadas', 33),
  ('unam-matematicas-aplicadas-y-computacion', 'unam', 'unam-a1', 'Matemáticas Aplicadas y Computación', 34),
  ('unam-matematicas-para-el-desarrollo', 'unam', 'unam-a1', 'Matemáticas para el Desarrollo', 35),
  ('unam-nanotecnologia', 'unam', 'unam-a1', 'Nanotecnología', 36),
  ('unam-tecnologias-para-la-informacion-en-ciencias', 'unam', 'unam-a1', 'Tecnologías para la Información en Ciencias', 37),
  ('unam-tecnologia', 'unam', 'unam-a1', 'Tecnología', 38),
  ('unam-urbanismo', 'unam', 'unam-a1', 'Urbanismo', 39),
  ('unam-biologia', 'unam', 'unam-a2', 'Biología', 40),
  ('unam-bioquimica-diagnostica', 'unam', 'unam-a2', 'Bioquímica Diagnóstica', 41),
  ('unam-ciencia-de-la-nutricion-humana', 'unam', 'unam-a2', 'Ciencia de la Nutrición Humana', 42),
  ('unam-ciencia-forense', 'unam', 'unam-a2', 'Ciencia Forense', 43),
  ('unam-ciencias-agrogenomicas', 'unam', 'unam-a2', 'Ciencias Agrogenómicas', 44),
  ('unam-ciencias-agroforestales', 'unam', 'unam-a2', 'Ciencias Agroforestales', 45),
  ('unam-ciencias-ambientales', 'unam', 'unam-a2', 'Ciencias Ambientales', 46),
  ('unam-ciencias-genomicas', 'unam', 'unam-a2', 'Ciencias Genómicas', 47),
  ('unam-cirujano-dentista', 'unam', 'unam-a2', 'Cirujano Dentista', 48),
  ('unam-ecologia', 'unam', 'unam-a2', 'Ecología', 49),
  ('unam-enfermeria', 'unam', 'unam-a2', 'Enfermería', 50),
  ('unam-enfermeria-y-obstetricia', 'unam', 'unam-a2', 'Enfermería y Obstetricia', 51),
  ('unam-farmacia', 'unam', 'unam-a2', 'Farmacia', 52),
  ('unam-fisioterapia', 'unam', 'unam-a2', 'Fisioterapia', 53),
  ('unam-ingenieria-agricola', 'unam', 'unam-a2', 'Ingeniería Agrícola', 54),
  ('unam-ingenieria-en-alimentos', 'unam', 'unam-a2', 'Ingeniería en Alimentos', 55),
  ('unam-investigacion-biomedica-basica', 'unam', 'unam-a2', 'Investigación Biomédica Básica', 56),
  ('unam-manejo-sustentable-de-zonas-costeras', 'unam', 'unam-a2', 'Manejo Sustentable de Zonas Costeras', 57),
  ('unam-medicina', 'unam', 'unam-a2', 'Médico Cirujano', 58),
  ('unam-medicina-veterinaria-y-zootecnia', 'unam', 'unam-a2', 'Medicina Veterinaria y Zootecnia', 59),
  ('unam-neurociencias', 'unam', 'unam-a2', 'Neurociencias', 60),
  ('unam-nutriologia', 'unam', 'unam-a2', 'Nutriología', 61),
  ('unam-optometria', 'unam', 'unam-a2', 'Optometría', 62),
  ('unam-ortesis-y-protesis', 'unam', 'unam-a2', 'Órtesis y Prótesis', 63),
  ('unam-psicologia', 'unam', 'unam-a2', 'Psicología', 64),
  ('unam-quimica', 'unam', 'unam-a2', 'Química', 65),
  ('unam-quimica-cosmetica-industrial', 'unam', 'unam-a2', 'Química Cosmética Industrial', 66),
  ('unam-quimica-de-alimentos', 'unam', 'unam-a2', 'Química de Alimentos', 67),
  ('unam-quimica-e-ingenieria-en-materiales', 'unam', 'unam-a2', 'Química e Ingeniería en Materiales', 68),
  ('unam-quimica-farmaceutico-biologica', 'unam', 'unam-a2', 'Química Farmacéutico Biológica', 69),
  ('unam-quimica-industrial', 'unam', 'unam-a2', 'Química Industrial', 70),
  ('unam-administracion', 'unam', 'unam-a3', 'Administración', 71),
  ('unam-administracion-agropecuaria', 'unam', 'unam-a3', 'Administración Agropecuaria', 72),
  ('unam-administracion-de-archivos-y-gestion-documental', 'unam', 'unam-a3', 'Administración de Archivos y Gestión Documental', 73),
  ('unam-antropologia', 'unam', 'unam-a3', 'Antropología', 74),
  ('unam-ciencias-de-la-comunicacion', 'unam', 'unam-a3', 'Ciencias de la Comunicación', 75),
  ('unam-ciencias-politicas-y-administracion-publica', 'unam', 'unam-a3', 'Ciencias Políticas y Administración Pública', 76),
  ('unam-comunicacion', 'unam', 'unam-a3', 'Comunicación', 77),
  ('unam-comunicacion-y-periodismo', 'unam', 'unam-a3', 'Comunicación y Periodismo', 78),
  ('unam-contaduria', 'unam', 'unam-a3', 'Contaduría', 79),
  ('unam-derecho', 'unam', 'unam-a3', 'Derecho', 80),
  ('unam-desarrollo-comunitario-para-el-envejecimiento', 'unam', 'unam-a3', 'Desarrollo Comunitario para el Envejecimiento', 81),
  ('unam-desarrollo-territorial', 'unam', 'unam-a3', 'Desarrollo Territorial', 82),
  ('unam-economia', 'unam', 'unam-a3', 'Economía', 83),
  ('unam-economia-industrial', 'unam', 'unam-a3', 'Economía Industrial', 84),
  ('unam-estudios-sociales-y-gestion-local', 'unam', 'unam-a3', 'Estudios Sociales y Gestión Local', 85),
  ('unam-geografia', 'unam', 'unam-a3', 'Geografía', 86),
  ('unam-geografia-aplicada', 'unam', 'unam-a3', 'Geografía Aplicada', 87),
  ('unam-informatica', 'unam', 'unam-a3', 'Informática', 88),
  ('unam-negocios-internacionales', 'unam', 'unam-a3', 'Negocios Internacionales', 89),
  ('unam-planificacion-para-el-desarrollo-agropecuario', 'unam', 'unam-a3', 'Planificación para el Desarrollo Agropecuario', 90),
  ('unam-relaciones-internacionales', 'unam', 'unam-a3', 'Relaciones Internacionales', 91),
  ('unam-sociologia', 'unam', 'unam-a3', 'Sociología', 92),
  ('unam-sociologia-aplicada', 'unam', 'unam-a3', 'Sociología Aplicada', 93),
  ('unam-trabajo-social', 'unam', 'unam-a3', 'Trabajo Social', 94),
  ('unam-turismo-y-desarrollo-sostenible', 'unam', 'unam-a3', 'Turismo y Desarrollo Sostenible', 95),
  ('unam-arte-y-diseno', 'unam', 'unam-a4', 'Arte y Diseño', 96),
  ('unam-artes-visuales', 'unam', 'unam-a4', 'Artes Visuales', 97),
  ('unam-bibliotecologia-y-estudios-de-la-informacion', 'unam', 'unam-a4', 'Bibliotecología y Estudios de la Información', 98),
  ('unam-cinematografia', 'unam', 'unam-a4', 'Cinematografía', 99),
  ('unam-desarrollo-y-gestion-interculturales', 'unam', 'unam-a4', 'Desarrollo y Gestión Interculturales', 100),
  ('unam-diseno-grafico', 'unam', 'unam-a4', 'Diseño Gráfico', 101),
  ('unam-diseno-y-comunicacion-visual', 'unam', 'unam-a4', 'Diseño y Comunicación Visual', 102),
  ('unam-ensenanza-del-aleman-como-lengua-extranjera', 'unam', 'unam-a4', 'Enseñanza del Alemán como Lengua Extranjera', 103),
  ('unam-ensenanza-del-espanol-como-lengua-extranjera', 'unam', 'unam-a4', 'Enseñanza del Español como Lengua Extranjera', 104),
  ('unam-ensenanza-del-frances-como-lengua-extranjera', 'unam', 'unam-a4', 'Enseñanza del Francés como Lengua Extranjera', 105),
  ('unam-ensenanza-del-ingles-como-lengua-extranjera', 'unam', 'unam-a4', 'Enseñanza del Inglés como Lengua Extranjera', 106),
  ('unam-ensenanza-del-italiano-como-lengua-extranjera', 'unam', 'unam-a4', 'Enseñanza del Italiano como Lengua Extranjera', 107),
  ('unam-estudios-latinoamericanos', 'unam', 'unam-a4', 'Estudios Latinoamericanos', 108),
  ('unam-etnomusicologia', 'unam', 'unam-a4', 'Etnomusicología', 109),
  ('unam-filosofia', 'unam', 'unam-a4', 'Filosofía', 110),
  ('unam-geohistoria', 'unam', 'unam-a4', 'Geohistoria', 111),
  ('unam-historia', 'unam', 'unam-a4', 'Historia', 112),
  ('unam-historia-del-arte', 'unam', 'unam-a4', 'Historia del Arte', 113),
  ('unam-instrumentista', 'unam', 'unam-a4', 'Instrumentista', 114),
  ('unam-lengua-y-literaturas-hispanicas', 'unam', 'unam-a4', 'Lengua y Literaturas Hispánicas', 115),
  ('unam-lengua-y-literaturas-modernas-alemanas', 'unam', 'unam-a4', 'Lengua y Literaturas Modernas (Alemanas)', 116),
  ('unam-lengua-y-literaturas-modernas-francesas', 'unam', 'unam-a4', 'Lengua y Literaturas Modernas (Francesas)', 117),
  ('unam-lengua-y-literaturas-modernas-inglesas', 'unam', 'unam-a4', 'Lengua y Literaturas Modernas (Inglesas)', 118),
  ('unam-lengua-y-literaturas-modernas-italianas', 'unam', 'unam-a4', 'Lengua y Literaturas Modernas (Italianas)', 119),
  ('unam-lengua-y-literaturas-modernas-portuguesas', 'unam', 'unam-a4', 'Lengua y Literaturas Modernas (Portuguesas)', 120),
  ('unam-letras-clasicas', 'unam', 'unam-a4', 'Letras Clásicas', 121),
  ('unam-linguistica-aplicada', 'unam', 'unam-a4', 'Lingüística Aplicada', 122),
  ('unam-literatura-dramatica-y-teatro', 'unam', 'unam-a4', 'Literatura Dramática y Teatro', 123),
  ('unam-literatura-intercultural', 'unam', 'unam-a4', 'Literatura Intercultural', 124),
  ('unam-musica-canto', 'unam', 'unam-a4', 'Música - Canto', 125),
  ('unam-musica-composicion', 'unam', 'unam-a4', 'Música - Composición', 126),
  ('unam-musica-educacion-musical', 'unam', 'unam-a4', 'Música - Educación Musical', 127),
  ('unam-musica-piano', 'unam', 'unam-a4', 'Música - Piano', 128),
  ('unam-musica-y-tecnologia-artistica', 'unam', 'unam-a4', 'Música y Tecnología Artística', 129),
  ('unam-pedagogia', 'unam', 'unam-a4', 'Pedagogía', 130),
  ('unam-teatro-y-actuacion', 'unam', 'unam-a4', 'Teatro y Actuación', 131),
  ('unam-traduccion', 'unam', 'unam-a4', 'Traducción', 132),
  ('ipn-ingenieria-aeronautica', 'ipn', 'ipn-a1', 'Ingeniería Aeronáutica', 1),
  ('ipn-ingenieria-bionica', 'ipn', 'ipn-a1', 'Ingeniería Biónica', 2),
  ('ipn-civil', 'ipn', 'ipn-a1', 'Ingeniería Civil', 3),
  ('ipn-ingenieria-en-computacion', 'ipn', 'ipn-a1', 'Ingeniería en Computación', 4),
  ('ipn-ingenieria-en-control-y-automatizacion', 'ipn', 'ipn-a1', 'Ingeniería en Control y Automatización', 5),
  ('ipn-ingenieria-en-comunicaciones-y-electronica', 'ipn', 'ipn-a1', 'Ingeniería en Comunicaciones y Electrónica', 6),
  ('ipn-ingenieria-en-inteligencia-artificial', 'ipn', 'ipn-a1', 'Ingeniería en Inteligencia Artificial', 7),
  ('ipn-ingenieria-en-robotica-industrial', 'ipn', 'ipn-a1', 'Ingeniería en Robótica Industrial', 8),
  ('ipn-sistemas', 'ipn', 'ipn-a1', 'Ingeniería en Sistemas Computacionales', 9),
  ('ipn-ingenieria-en-sistemas-automotrices', 'ipn', 'ipn-a1', 'Ingeniería en Sistemas Automotrices', 10),
  ('ipn-ingenieria-mecanica', 'ipn', 'ipn-a1', 'Ingeniería Mecánica', 11),
  ('ipn-mecatronica', 'ipn', 'ipn-a1', 'Ingeniería Mecatrónica', 12),
  ('ipn-ingenieria-metalurgica', 'ipn', 'ipn-a1', 'Ingeniería Metalúrgica', 13),
  ('ipn-ingenieria-petrolera', 'ipn', 'ipn-a1', 'Ingeniería Petrolera', 14),
  ('ipn-ingenieria-quimica-industrial', 'ipn', 'ipn-a1', 'Ingeniería Química Industrial', 15),
  ('ipn-ingenieria-quimica-petrolera', 'ipn', 'ipn-a1', 'Ingeniería Química Petrolera', 16),
  ('ipn-ingenieria-textil', 'ipn', 'ipn-a1', 'Ingeniería Textil', 17),
  ('ipn-ingenieria-topografica-y-fotogrametrica', 'ipn', 'ipn-a1', 'Ingeniería Topográfica y Fotogramétrica', 18),
  ('ipn-ingenieria-en-transporte', 'ipn', 'ipn-a1', 'Ingeniería en Transporte', 19),
  ('ipn-licenciatura-en-fisica-y-matematicas', 'ipn', 'ipn-a1', 'Licenciatura en Física y Matemáticas', 20),
  ('ipn-licenciatura-en-ciencias-de-la-informatica', 'ipn', 'ipn-a1', 'Licenciatura en Ciencias de la Informática', 21),
  ('ipn-ingenieria-fotonica', 'ipn', 'ipn-a1', 'Ingeniería Fotónica', 22),
  ('ipn-ingenieria-geofisica', 'ipn', 'ipn-a1', 'Ingeniería Geofísica', 23),
  ('ipn-ingenieria-geologica', 'ipn', 'ipn-a1', 'Ingeniería Geológica', 24),
  ('ipn-ingenieria-en-movilidad-urbana', 'ipn', 'ipn-a1', 'Ingeniería en Movilidad Urbana', 25),
  ('ipn-ingenieria-ambiental-a1', 'ipn', 'ipn-a1', 'Ingeniería Ambiental', 26),
  ('ipn-ingenieria-farmaceutica', 'ipn', 'ipn-a1', 'Ingeniería Farmacéutica', 27),
  ('ipn-ingenieria-biomedica', 'ipn', 'ipn-a1', 'Ingeniería Biomédica', 28),
  ('ipn-medico', 'ipn', 'ipn-a2', 'Médico Cirujano y Partero', 29),
  ('ipn-medico-cirujano-y-homeopata', 'ipn', 'ipn-a2', 'Médico Cirujano y Homeópata', 30),
  ('ipn-licenciatura-en-enfermeria', 'ipn', 'ipn-a2', 'Licenciatura en Enfermería', 31),
  ('ipn-licenciatura-en-enfermeria-y-obstetricia', 'ipn', 'ipn-a2', 'Licenciatura en Enfermería y Obstetricia', 32),
  ('ipn-licenciatura-en-odontologia', 'ipn', 'ipn-a2', 'Licenciatura en Odontología', 33),
  ('ipn-licenciatura-en-optometria', 'ipn', 'ipn-a2', 'Licenciatura en Optometría', 34),
  ('ipn-licenciatura-en-nutricion', 'ipn', 'ipn-a2', 'Licenciatura en Nutrición', 35),
  ('ipn-licenciatura-en-trabajo-social', 'ipn', 'ipn-a2', 'Licenciatura en Trabajo Social', 36),
  ('ipn-quimico-bacteriologo-parasitologo', 'ipn', 'ipn-a2', 'Químico Bacteriólogo Parasitólogo', 37),
  ('ipn-licenciatura-en-biologia', 'ipn', 'ipn-a2', 'Licenciatura en Biología', 38),
  ('ipn-ingenieria-biotecnologica', 'ipn', 'ipn-a2', 'Ingeniería Biotecnológica', 39),
  ('ipn-ingenieria-bioquimica', 'ipn', 'ipn-a2', 'Ingeniería Bioquímica', 40),
  ('ipn-ingenieria-ambiental-a2', 'ipn', 'ipn-a2', 'Ingeniería Ambiental', 41),
  ('ipn-licenciatura-en-administracion-industrial', 'ipn', 'ipn-a3', 'Licenciatura en Administración Industrial', 42),
  ('ipn-licenciatura-en-contaduria-publica', 'ipn', 'ipn-a3', 'Licenciatura en Contaduría Pública', 43),
  ('ipn-licenciatura-en-comercio-internacional', 'ipn', 'ipn-a3', 'Licenciatura en Comercio Internacional', 44),
  ('ipn-licenciatura-en-economia', 'ipn', 'ipn-a3', 'Licenciatura en Economía', 45),
  ('ipn-licenciatura-en-negocios-digitales', 'ipn', 'ipn-a3', 'Licenciatura en Negocios Digitales', 46),
  ('ipn-licenciatura-en-relaciones-comerciales', 'ipn', 'ipn-a3', 'Licenciatura en Relaciones Comerciales', 47),
  ('ipn-licenciatura-en-turismo', 'ipn', 'ipn-a3', 'Licenciatura en Turismo', 48),
  ('ipn-licenciatura-en-mercadotecnia-digital', 'ipn', 'ipn-a3', 'Licenciatura en Mercadotecnia Digital', 49),
  ('uam-ingenieria-ambiental', 'uam', 'uam-cbi', 'Ingeniería Ambiental', 1),
  ('uam-ing-biomedica', 'uam', 'uam-cbi', 'Ingeniería Biomédica', 2),
  ('uam-ingenieria-civil', 'uam', 'uam-cbi', 'Ingeniería Civil', 3),
  ('uam-ingenieria-computacional', 'uam', 'uam-cbi', 'Ingeniería Computacional', 4),
  ('uam-ingenieria-electrica', 'uam', 'uam-cbi', 'Ingeniería Eléctrica', 5),
  ('uam-ingenieria-electronica', 'uam', 'uam-cbi', 'Ingeniería Electrónica', 6),
  ('uam-ingenieria-energetica', 'uam', 'uam-cbi', 'Ingeniería Energética', 7),
  ('uam-ingenieria-fisico-industrial', 'uam', 'uam-cbi', 'Ingeniería Físico-Industrial', 8),
  ('uam-ingenieria-hidrologica', 'uam', 'uam-cbi', 'Ingeniería Hidrológica', 9),
  ('uam-ingenieria-industrial', 'uam', 'uam-cbi', 'Ingeniería Industrial', 10),
  ('uam-ingenieria-mecanica', 'uam', 'uam-cbi', 'Ingeniería Mecánica', 11),
  ('uam-ingenieria-quimica', 'uam', 'uam-cbi', 'Ingeniería Química', 12),
  ('uam-licenciatura-en-computacion', 'uam', 'uam-cbi', 'Licenciatura en Computación', 13),
  ('uam-licenciatura-en-fisica', 'uam', 'uam-cbi', 'Licenciatura en Física', 14),
  ('uam-licenciatura-en-matematicas', 'uam', 'uam-cbi', 'Licenciatura en Matemáticas', 15),
  ('uam-licenciatura-en-quimica', 'uam', 'uam-cbi', 'Licenciatura en Química', 16),
  ('uam-ingenieria-agronomica', 'uam', 'uam-cbs', 'Ingeniería Agronómica', 17),
  ('uam-ingenieria-bioquimica-industrial', 'uam', 'uam-cbs', 'Ingeniería Bioquímica Industrial', 18),
  ('uam-licenciatura-en-biologia', 'uam', 'uam-cbs', 'Licenciatura en Biología', 19),
  ('uam-licenciatura-en-biologia-experimental', 'uam', 'uam-cbs', 'Licenciatura en Biología Experimental', 20),
  ('uam-licenciatura-en-enfermeria', 'uam', 'uam-cbs', 'Licenciatura en Enfermería', 21),
  ('uam-licenciatura-en-estomatologia', 'uam', 'uam-cbs', 'Licenciatura en Estomatología', 22),
  ('uam-licenciatura-en-medicina-veterinaria-y-zootecnia', 'uam', 'uam-cbs', 'Licenciatura en Medicina Veterinaria y Zootecnia', 23),
  ('uam-licenciatura-en-medicina', 'uam', 'uam-cbs', 'Licenciatura en Medicina', 24),
  ('uam-nutricion', 'uam', 'uam-cbs', 'Licenciatura en Nutrición Humana', 25),
  ('uam-licenciatura-en-quimica-farmaceutica-biologica', 'uam', 'uam-cbs', 'Licenciatura en Química Farmacéutica Biológica', 26),
  ('uam-administracion', 'uam', 'uam-csh', 'Licenciatura en Administración', 27),
  ('uam-licenciatura-en-antropologia-social', 'uam', 'uam-csh', 'Licenciatura en Antropología Social', 28),
  ('uam-licenciatura-en-ciencia-politica', 'uam', 'uam-csh', 'Licenciatura en Ciencia Política', 29),
  ('uam-licenciatura-en-comunicacion-social-csh', 'uam', 'uam-csh', 'Licenciatura en Comunicación Social', 30),
  ('uam-licenciatura-en-derecho', 'uam', 'uam-csh', 'Licenciatura en Derecho', 31),
  ('uam-licenciatura-en-economia', 'uam', 'uam-csh', 'Licenciatura en Economía', 32),
  ('uam-licenciatura-en-filosofia', 'uam', 'uam-csh', 'Licenciatura en Filosofía', 33),
  ('uam-licenciatura-en-geografia-humana', 'uam', 'uam-csh', 'Licenciatura en Geografía Humana', 34),
  ('uam-licenciatura-en-historia', 'uam', 'uam-csh', 'Licenciatura en Historia', 35),
  ('uam-licenciatura-en-letras-hispanicas', 'uam', 'uam-csh', 'Licenciatura en Letras Hispánicas', 36),
  ('uam-licenciatura-en-linguistica', 'uam', 'uam-csh', 'Licenciatura en Lingüística', 37),
  ('uam-licenciatura-en-psicologia', 'uam', 'uam-csh', 'Licenciatura en Psicología', 38),
  ('uam-licenciatura-en-psicologia-social', 'uam', 'uam-csh', 'Licenciatura en Psicología Social', 39),
  ('uam-licenciatura-en-sociologia', 'uam', 'uam-csh', 'Licenciatura en Sociología', 40),
  ('uam-licenciatura-en-politologia', 'uam', 'uam-csh', 'Licenciatura en Politología', 41),
  ('uam-licenciatura-en-arquitectura', 'uam', 'uam-cad', 'Licenciatura en Arquitectura', 42),
  ('uam-diseno', 'uam', 'uam-cad', 'Licenciatura en Diseño de la Comunicación Gráfica', 43),
  ('uam-licenciatura-en-diseno-industrial', 'uam', 'uam-cad', 'Licenciatura en Diseño Industrial', 44),
  ('uam-licenciatura-en-planeacion-territorial', 'uam', 'uam-cad', 'Licenciatura en Planeación Territorial', 45),
  ('uam-licenciatura-en-ciencias-de-la-informacion', 'uam', 'uam-ccd', 'Licenciatura en Ciencias de la Información', 46),
  ('uam-licenciatura-en-comunicacion-social-ccd', 'uam', 'uam-ccd', 'Licenciatura en Comunicación Social', 47),
  ('uam-licenciatura-en-diseno', 'uam', 'uam-ccd', 'Licenciatura en Diseño', 48),
  ('uam-licenciatura-en-biologia-molecular', 'uam', 'uam-cni', 'Licenciatura en Biología Molecular', 49),
  ('uam-ingenieria-biologica', 'uam', 'uam-cni', 'Ingeniería Biológica', 50),
  ('uam-licenciatura-en-matematicas-aplicadas', 'uam', 'uam-cni', 'Licenciatura en Matemáticas Aplicadas', 51),
  ('udg-ingenieria-civil', 'udg', 'udg-cucei', 'Ingeniería Civil', 1),
  ('udg-ingenieria-en-computacion', 'udg', 'udg-cucei', 'Ingeniería en Computación', 2),
  ('udg-informatica', 'udg', 'udg-cucei', 'Ingeniería en Informática', 3),
  ('udg-ingenieria-biomedica', 'udg', 'udg-cucei', 'Ingeniería Biomédica', 4),
  ('udg-ingenieria-fotonica', 'udg', 'udg-cucei', 'Ingeniería Fotónica', 5),
  ('udg-ingenieria-robotica', 'udg', 'udg-cucei', 'Ingeniería Robótica', 6),
  ('udg-ingenieria-industrial', 'udg', 'udg-cucei', 'Ingeniería Industrial', 7),
  ('udg-ingenieria-mecanica-electrica', 'udg', 'udg-cucei', 'Ingeniería Mecánica Eléctrica', 8),
  ('udg-ingenieria-quimica', 'udg', 'udg-cucei', 'Ingeniería Química', 9),
  ('udg-ingenieria-de-alimentos', 'udg', 'udg-cucei', 'Ingeniería de Alimentos', 10),
  ('udg-licenciatura-en-fisica', 'udg', 'udg-cucei', 'Licenciatura en Física', 11),
  ('udg-licenciatura-en-matematicas', 'udg', 'udg-cucei', 'Licenciatura en Matemáticas', 12),
  ('udg-licenciatura-en-quimica', 'udg', 'udg-cucei', 'Licenciatura en Química', 13),
  ('udg-licenciatura-en-quimico-farmaceutico-biologo', 'udg', 'udg-cucei', 'Licenciatura en Químico Farmacéutico Biólogo', 14),
  ('udg-medicina', 'udg', 'udg-cucs', 'Médico Cirujano y Partero', 15),
  ('udg-licenciatura-en-cirujano-dentista', 'udg', 'udg-cucs', 'Licenciatura en Cirujano Dentista', 16),
  ('udg-enfermeria', 'udg', 'udg-cucs', 'Licenciatura en Enfermería', 17),
  ('udg-licenciatura-en-nutricion', 'udg', 'udg-cucs', 'Licenciatura en Nutrición', 18),
  ('udg-licenciatura-en-psicologia', 'udg', 'udg-cucs', 'Licenciatura en Psicología', 19),
  ('udg-licenciatura-en-cultura-fisica-y-deporte', 'udg', 'udg-cucs', 'Licenciatura en Cultura Física y Deporte', 20),
  ('udg-licenciatura-en-podologia', 'udg', 'udg-cucs', 'Licenciatura en Podología', 21),
  ('udg-licenciatura-en-administracion', 'udg', 'udg-cucea', 'Licenciatura en Administración', 22),
  ('udg-licenciatura-en-contaduria-publica', 'udg', 'udg-cucea', 'Licenciatura en Contaduría Pública', 23),
  ('udg-licenciatura-en-economia', 'udg', 'udg-cucea', 'Licenciatura en Economía', 24),
  ('udg-licenciatura-en-mercadotecnia', 'udg', 'udg-cucea', 'Licenciatura en Mercadotecnia', 25),
  ('udg-licenciatura-en-negocios-internacionales', 'udg', 'udg-cucea', 'Licenciatura en Negocios Internacionales', 26),
  ('udg-licenciatura-en-turismo', 'udg', 'udg-cucea', 'Licenciatura en Turismo', 27),
  ('udg-licenciatura-en-ingenieria-en-negocios', 'udg', 'udg-cucea', 'Licenciatura en Ingeniería en Negocios', 28),
  ('udg-licenciatura-en-tecnologias-de-la-informacion', 'udg', 'udg-cucea', 'Licenciatura en Tecnologías de la Información', 29),
  ('udg-abogado', 'udg', 'udg-cucsh', 'Licenciatura en Abogado / Derecho', 30),
  ('udg-licenciatura-en-relaciones-internacionales', 'udg', 'udg-cucsh', 'Licenciatura en Relaciones Internacionales', 31),
  ('udg-licenciatura-en-sociologia', 'udg', 'udg-cucsh', 'Licenciatura en Sociología', 32),
  ('udg-licenciatura-en-trabajo-social', 'udg', 'udg-cucsh', 'Licenciatura en Trabajo Social', 33),
  ('udg-licenciatura-en-historia', 'udg', 'udg-cucsh', 'Licenciatura en Historia', 34),
  ('udg-licenciatura-en-filosofia', 'udg', 'udg-cucsh', 'Licenciatura en Filosofía', 35),
  ('udg-licenciatura-en-letras-hispanicas', 'udg', 'udg-cucsh', 'Licenciatura en Letras Hispánicas', 36),
  ('udg-licenciatura-en-arquitectura', 'udg', 'udg-cuaad', 'Licenciatura en Arquitectura', 37),
  ('udg-licenciatura-en-disenador-para-la-comunicacion-grafica', 'udg', 'udg-cuaad', 'Licenciatura en Diseñador para la Comunicación Gráfica', 38),
  ('udg-licenciatura-en-diseno-industrial', 'udg', 'udg-cuaad', 'Licenciatura en Diseño Industrial', 39),
  ('udg-licenciatura-en-artes-visuales', 'udg', 'udg-cuaad', 'Licenciatura en Artes Visuales', 40),
  ('udg-licenciatura-en-musica', 'udg', 'udg-cuaad', 'Licenciatura en Música', 41),
  ('udg-licenciatura-en-biologia', 'udg', 'udg-cucba', 'Licenciatura en Biología', 42),
  ('udg-licenciatura-en-agronomia', 'udg', 'udg-cucba', 'Licenciatura en Agronomía', 43),
  ('udg-licenciatura-en-medicina-veterinaria-y-zootecnia', 'udg', 'udg-cucba', 'Licenciatura en Medicina Veterinaria y Zootecnia', 44),
  ('udg-licenciatura-en-ciencia-de-los-alimentos', 'udg', 'udg-cucba', 'Licenciatura en Ciencia de los Alimentos', 45),
  ('uanl-medico-cirujano-y-partero', 'uanl', 'uanl-a1', 'Médico Cirujano y Partero', 1),
  ('uanl-cirujano-dentista', 'uanl', 'uanl-a1', 'Cirujano Dentista', 2),
  ('uanl-licenciado-en-enfermeria', 'uanl', 'uanl-a1', 'Licenciado en Enfermería', 3),
  ('uanl-licenciado-en-nutricion', 'uanl', 'uanl-a1', 'Licenciado en Nutrición', 4),
  ('uanl-licenciado-en-psicologia', 'uanl', 'uanl-a1', 'Licenciado en Psicología', 5),
  ('uanl-quimico-farmaceutico-biologo', 'uanl', 'uanl-a1', 'Químico Farmacéutico Biólogo', 6),
  ('uanl-ingeniero-mecanico-administrador', 'uanl', 'uanl-a2', 'Ingeniero Mecánico Administrador', 7),
  ('uanl-ingeniero-mecanico-electricista', 'uanl', 'uanl-a2', 'Ingeniero Mecánico Electricista', 8),
  ('uanl-ingeniero-mecatronico', 'uanl', 'uanl-a2', 'Ingeniero Mecatrónico', 9),
  ('uanl-ingeniero-en-tecnologias-de-la-computacion', 'uanl', 'uanl-a2', 'Ingeniero en Tecnologías de la Computación', 10),
  ('uanl-ingeniero-industrial-y-de-sistemas', 'uanl', 'uanl-a2', 'Ingeniero Industrial y de Sistemas', 11),
  ('uanl-ingeniero-civil', 'uanl', 'uanl-a2', 'Ingeniero Civil', 12),
  ('uanl-ingeniero-quimico', 'uanl', 'uanl-a2', 'Ingeniero Químico', 13),
  ('uanl-ingeniero-biomedico', 'uanl', 'uanl-a2', 'Ingeniero Biomédico', 14),
  ('uanl-ingeniero-aeronautico', 'uanl', 'uanl-a2', 'Ingeniero Aeronáutico', 15),
  ('uanl-ingeniero-en-software', 'uanl', 'uanl-a2', 'Ingeniero en Software', 16),
  ('uanl-licenciado-en-ciencias-computacionales', 'uanl', 'uanl-a3', 'Licenciado en Ciencias Computacionales', 17),
  ('uanl-licenciado-en-actuaria', 'uanl', 'uanl-a3', 'Licenciado en Actuaría', 18),
  ('uanl-licenciado-en-fisica', 'uanl', 'uanl-a3', 'Licenciado en Física', 19),
  ('uanl-licenciado-en-matematicas', 'uanl', 'uanl-a3', 'Licenciado en Matemáticas', 20),
  ('uanl-licenciado-en-derecho', 'uanl', 'uanl-a4', 'Licenciado en Derecho', 21),
  ('uanl-licenciado-en-criminologia', 'uanl', 'uanl-a4', 'Licenciado en Criminología', 22),
  ('uanl-licenciado-en-relaciones-internacionales', 'uanl', 'uanl-a4', 'Licenciado en Relaciones Internacionales', 23),
  ('uanl-licenciado-en-ciencias-politicas-y-administracion-publica', 'uanl', 'uanl-a4', 'Licenciado en Ciencias Políticas y Administración Pública', 24),
  ('uanl-licenciado-en-ciencias-de-la-comunicacion', 'uanl', 'uanl-a4', 'Licenciado en Ciencias de la Comunicación', 25),
  ('uanl-licenciado-en-sociologia', 'uanl', 'uanl-a4', 'Licenciado en Sociología', 26),
  ('uanl-licenciado-en-administracion', 'uanl', 'uanl-a5', 'Licenciado en Administración', 27),
  ('uanl-licenciado-en-contador-publico', 'uanl', 'uanl-a5', 'Licenciado en Contador Público', 28),
  ('uanl-licenciado-en-economia', 'uanl', 'uanl-a5', 'Licenciado en Economía', 29),
  ('uanl-licenciado-en-negocios-internacionales', 'uanl', 'uanl-a5', 'Licenciado en Negocios Internacionales', 30),
  ('uanl-licenciado-en-mercadotecnia', 'uanl', 'uanl-a5', 'Licenciado en Mercadotecnia', 31),
  ('uanl-licenciado-en-arquitectura', 'uanl', 'uanl-a6', 'Licenciado en Arquitectura', 32),
  ('uanl-licenciado-en-diseno-industrial', 'uanl', 'uanl-a6', 'Licenciado en Diseño Industrial', 33),
  ('uanl-licenciado-en-artes-visuales', 'uanl', 'uanl-a6', 'Licenciado en Artes Visuales', 34),
  ('uanl-licenciado-en-diseno-grafico', 'uanl', 'uanl-a6', 'Licenciado en Diseño Gráfico', 35),
  ('buap-ingenieria-civil', 'buap', 'buap-a1', 'Ingeniería Civil', 1),
  ('buap-ingenieria-ciencias-de-la-computacion', 'buap', 'buap-a1', 'Ingeniería Ciencias de la Computación', 2),
  ('buap-ingenieria-en-ciencias-de-la-electronica', 'buap', 'buap-a1', 'Ingeniería en Ciencias de la Electrónica', 3),
  ('buap-ingenieria-industrial', 'buap', 'buap-a1', 'Ingeniería Industrial', 4),
  ('buap-ingenieria-mecanica-y-electrica', 'buap', 'buap-a1', 'Ingeniería Mecánica y Eléctrica', 5),
  ('buap-ingenieria-mecatronica', 'buap', 'buap-a1', 'Ingeniería Mecatrónica', 6),
  ('buap-ingenieria-quimica', 'buap', 'buap-a1', 'Ingeniería Química', 7),
  ('buap-ingenieria-ambiental', 'buap', 'buap-a1', 'Ingeniería Ambiental', 8),
  ('buap-licenciatura-en-arquitectura', 'buap', 'buap-a1', 'Licenciatura en Arquitectura', 9),
  ('buap-licenciatura-en-diseno-grafico', 'buap', 'buap-a1', 'Licenciatura en Diseño Gráfico', 10),
  ('buap-licenciatura-en-medicina', 'buap', 'buap-a2', 'Licenciatura en Medicina', 11),
  ('buap-licenciatura-en-stomatologia-odontologia', 'buap', 'buap-a2', 'Licenciatura en Stomatología / Odontología', 12),
  ('buap-licenciatura-en-enfermeria', 'buap', 'buap-a2', 'Licenciatura en Enfermería', 13),
  ('buap-licenciatura-en-nutricion-clinica', 'buap', 'buap-a2', 'Licenciatura en Nutrición Clínica', 14),
  ('buap-licenciatura-en-fisioterapia', 'buap', 'buap-a2', 'Licenciatura en Fisioterapia', 15),
  ('buap-licenciatura-en-biomedicina', 'buap', 'buap-a2', 'Licenciatura en Biomedicina', 16),
  ('buap-licenciatura-en-criminologia', 'buap', 'buap-a2', 'Licenciatura en Criminología', 17),
  ('buap-licenciatura-en-derecho', 'buap', 'buap-a3', 'Licenciatura en Derecho', 18),
  ('buap-licenciatura-en-relaciones-internacionales', 'buap', 'buap-a3', 'Licenciatura en Relaciones Internacionales', 19),
  ('buap-licenciatura-en-ciencias-politicas', 'buap', 'buap-a3', 'Licenciatura en Ciencias Políticas', 20),
  ('buap-licenciatura-en-administracion-de-empresas', 'buap', 'buap-a3', 'Licenciatura en Administración de Empresas', 21),
  ('buap-licenciatura-en-contaduria-publica', 'buap', 'buap-a3', 'Licenciatura en Contaduría Pública', 22),
  ('buap-licenciatura-en-economia', 'buap', 'buap-a3', 'Licenciatura en Economía', 23),
  ('buap-licenciatura-en-comercio-internacional', 'buap', 'buap-a3', 'Licenciatura en Comercio Internacional', 24),
  ('buap-licenciatura-en-comunicacion', 'buap', 'buap-a3', 'Licenciatura en Comunicación', 25),
  ('buap-licenciatura-en-psicologia', 'buap', 'buap-a4', 'Licenciatura en Psicología', 26),
  ('buap-licenciatura-en-filosofia', 'buap', 'buap-a4', 'Licenciatura en Filosofía', 27),
  ('buap-licenciatura-en-historia', 'buap', 'buap-a4', 'Licenciatura en Historia', 28),
  ('buap-licenciatura-en-linguistica-y-literatura-hispanica', 'buap', 'buap-a4', 'Licenciatura en Lingüística y Literatura Hispánica', 29),
  ('buap-licenciatura-en-lenguas-modernas', 'buap', 'buap-a4', 'Licenciatura en Lenguas Modernas', 30),
  ('toefl', 'toefl', null, 'TOEFL', 1);

commit;
